### ISSUE TITLE
pop numbers, but doesn't work. Says failured.

### ISSUE THREAD

**Issue by markshi9008** [brismuth/google-voice-bulk-texter#224] opened 2023-04-12 18:16 UTC
I was using the firebox browser, and I pasted a few numbers in the blanket for a test but failed.

**Comment by markshi9008** [comment] 2023-04-12 18:21
"writemessage failed"

**Comment by brismuth** [comment] 2023-04-13 19:23
Actually, this is a duplicate of #218, so feel free to read over that thread and comment - that thread is blocked until someone is able to provide the steps I listed to update Bulk Texter Lite.

**Closed as completed by brismuth** 2023-04-13 19:23 UTC
Labels: duplicate
