### ISSUE TITLE
ConfirmSent error

### ISSUE THREAD

**Issue by yatooka** [brismuth/google-voice-bulk-texter#31] opened 2019-01-23 06:47 UTC
First time use of Bulk-Texter. Upon review, same issue as issue #18.  I was in my Google Voice webpage. Had 13 text messages to send.  11 were sent successfully and last two perpetually failed.  I am using the following variable and phone number format:

{name}   -  in the text message body

(123) 555-1212, Name

For the two failing ones, the area codes are different. Messaging is not activated in Hangouts.  I suspect that Google trapped the message as spam and throttling. As a test, I sent a short text to my own number, the text went through fine...if I send the originally intended longer message to my number, it fails.  See error message in attached screenshot.  Have you ever heard if this issue on the Google end resets itself after a length of time or anything like that?  Thank you.

![screen shot 2019-01-23 at 1 22 05 am](https://user-images.githubusercontent.com/46953283/51587572-32172b00-1eaf-11e9-83aa-a5182484903a.png)

**Comment by brismuth** [comment] 2019-01-23 06:49
If you send the original longer message to your number manually (without the extension), does it fail then too? And does Google Voice give you an error message about it?

**Comment by yatooka** [comment] 2019-01-23 06:55
Yes, if I manually send it to myself, and of course in the body of the text replace the variable {name} with my name, it fails as well with “Message not sent”.  That demonstrates to me that Google is seeing something and not passing it on.  Maybe their algorithm analyzed the body of my original longer text message and watches for it…  I’m going to send a long message to myself here in a minute but with different text.

**Comment by brismuth** [comment] 2019-01-23 06:57
Thanks for confirming that. That does sound like the case. There are a couple Google voice forum links at the bottom of #18 that talk about Google's algorithms. That's about all the info I have about it.

**Comment by yatooka** [comment] 2019-01-23 07:02
Yeah, its something with them.  In these sample screenshots, the short message manually sent to myself shot through with no problem.  The longer one (random paragraph pasted in) would not deliver.
I can’t tell if it is an algorithm thing or a character limitation thing now… will just watch and see.  Thanks.

**Comment by brismuth** [comment] 2019-01-23 07:04
Looks like the screenshots didn't come through. Can you go to the GitHub site to upload those?

**Comment by yatooka** [comment] 2019-01-23 07:05
Yes, give me a sec.

**Comment by yatooka** [comment] 2019-01-23 07:06
Here are those two screenshots.  One is the two test texts; the second is just the fail message  in my text history.

![screen shot 2019-01-23 at 1 58 02 am](https://user-images.githubusercontent.com/46953283/51588946-7efd0080-1eb3-11e9-9e58-4c9abe532cb6.png)
![screen shot 2019-01-23 at 1 58 17 am](https://user-images.githubusercontent.com/46953283/51588949-7efd0080-1eb3-11e9-8de2-6d8836ecab32.png)

**Comment by yatooka** [comment] 2019-01-23 07:30
Here is something interesting:

"The limit is derived partially on how you send text messages with Google Voice. Certain activity can suggest spam, so Google puts a 24 hour hold on accounts who are detected as potential spammers. ... Also it is good to have multiple google voice accounts to send your text messages.  Sep 8, 2017"

https://www.leadtrafficnetwork.com/blog/what-is-google-voice-sending-limit-how-to-send-out

**Comment by brismuth** [comment] 2019-01-26 05:49
Thanks for the additional info, that's all really helpful.

I'm going to go ahead and close this as a duplicate of #18, so feel free to subscribe to that for updates.

**Closed by brismuth** 2019-01-26 05:49 UTC

**Comment by justamor** [comment] 2019-01-26 18:05
Im still having the same issues after troubleshooting...

**Comment by yourshawng** [comment] 2019-05-07 17:20
Same issue. read other post and shortened message and took link out. Same result
