### ISSUE TITLE
Messages not sending

### ISSUE THREAD

**Issue by snarfamthewiz** [brismuth/google-voice-bulk-texter#86] opened 2019-08-12 17:13 UTC
**Describe the bug**
The extension will fill in the phone number and messages, then rest without the message ever sending. For example, if I am sending a message to 123-456-7890, the message will be filled in. act like its sent and moving on to the next phone number in my string but will then fill back in with 123-456-7890 without ever sending the message.
**URL**
https://voice.google.com/messages?itemId=draft-AE841E87-6CCE-4C09-8F4C-85E8D7E6F828

**Expected behavior**
To iterate down the list sending individual messages properly 
**Screenshots**

**Additional context**

**Comment by brismuth** [comment] 2019-08-12 20:17
I'm not able to reproduce this issue on my end. Was it working for you before? And if you try a simple "test" message to your own phone number, does that send successfully?

**Comment by mrmikeray** [comment] 2019-08-13 16:58
Hi, I was using the extension for about a week. It disappeared from my extension & I can't find it in the Google Chrome Store anymore. Is it discontinued? Please send me link to get it back if available!

**Comment by brismuth** [comment] 2019-08-13 20:02
@mrmikeray yes, it was removed by Google. Follow these instructions to install it from source code:
https://github.com/brismuth/google-voice-bulk-texter#install-it

**Comment by mrmikeray** [comment] 2019-08-13 23:28
Got it! Thank you so much man. It's really a great extension!

**Comment by brismuth** [comment] 2019-09-09 03:11
Closing as duplicate of #87. Feel free to subscribe to that issue for updates.

**Closed by brismuth** 2019-09-09 03:11 UTC
