### ISSUE TITLE
Mass text only sends to the first number

### ISSUE THREAD

**Issue by crivera305** [brismuth/google-voice-bulk-texter#90] opened 2019-08-30 18:42 UTC
**Describe the bug**
When i fill out a list of numbers, names.... and run it - it does the first number on the list correctly, but when its time to iterate thru the list of numbers it continues to try to text the first number on the list - never moves on to the rest of the numbers

**URL**
https://voice.google.com/u/1/messages

**Expected behavior**
When i fill out a list of numbers, names.... and run it. it should iterate thru the list sending SMS messages to the complete list.

**Screenshots**
https://ibb.co/Dkf7hBH

**Additional context**
i downloaded the zip and installed it. looks like it works but only SMS the first name on the list

**Comment by mmedaugh** [comment] 2019-09-03 17:52
+1

**Comment by brismuth** [comment] 2019-09-09 03:14
Even though this isn't exactly the same issue, I'm going to close it as a duplicate of #87. Both are almost certainly caused by updates to the Google Voice UI that Google hasn't fully rolled out yet. Once they've rolled out the changes to me I'll update the code to handle this issue. Feel free to subscribe to that issue for updates.

**Closed by brismuth** 2019-09-09 03:14 UTC
