### ISSUE TITLE
unknown `Error: "showNumberInput"`

### ISSUE THREAD

**Issue by marafa** [brismuth/google-voice-bulk-texter#148] opened 2021-05-15 16:17 UTC
Got this error just now. Trying to send myself a test message. Support doc doesnt have this errror. I suspect i put a space after the comma. As the next one without the space was sent

```
Google Voice bulk texter v1.3.2:
Text failed. You can find support resources by opening the Google Voice Bulk Texter popup and clicking "Get Help" at the bottom.

Error: "showNumberInput" failed. 

When you click "ok" the page will refresh.
```
![Screenshot_20210515_121202](https://user-images.githubusercontent.com/1518315/118370735-13a13600-b577-11eb-9166-6ede5c9e8bae.png)

**Comment by brismuth** [comment] 2021-06-30 03:35
Thanks for filing. Looks like a dupe of #145 - if this is still happening for you, can you comment on that issue?

**Closed by brismuth** 2021-06-30 03:35 UTC
