### ISSUE TITLE
startChat Error message

### ISSUE THREAD

**Issue by Crossroadsnola** [brismuth/google-voice-bulk-texter#81] opened 2019-07-30 18:12 UTC
**Describe the bug**
Attempting to send text message to contact list. Has worked previously but now receiving a statChat error.

**URL**
No URL - Google Voice Bulk Texter widget

**Expected behavior**
After pressing "Send Message" button, expected chat widget to execute.

**Screenshots**

![Screen Shot 2019-07-30 at 1 07 00 PM](https://user-images.githubusercontent.com/53485164/62154096-ae118600-b2cb-11e9-8316-ad64c73ef6d7.png)
![Screen Shot 2019-07-30 at 1 08 51 PM](https://user-images.githubusercontent.com/53485164/62154098-ae118600-b2cb-11e9-805e-419cd6859534.png)

**Comment by brismuth** [comment] 2019-07-30 23:38
Duplicate of #75, which is now resolved. You'll need to manually update the extension following these instructions.
https://github.com/brismuth/google-voice-bulk-texter/blob/master/README.md#install-it

**Closed by brismuth** 2019-07-30 23:38 UTC
