### ISSUE TITLE
Error: "writeMessage" failed

### ISSUE THREAD

**Issue by crispycritter54** [brismuth/google-voice-bulk-texter#112] opened 2020-02-21 01:42 UTC
I can send messages manually but not through the bulk-texter. It was working fine 2 days ago. It loops on the same number for 6 times and then a box pops up with the write message failed error. 

**URL**
https://voice.google.com/u/0/messages

**Expected behavior**
Expected to send a message to a few phone numbers.

**Comment by brismuth** [comment] 2020-02-21 04:05
Thanks for reporting. 

Looks like this is a duplicate of #111. You should subscribe to updates on that issue.

**Closed by brismuth** 2020-02-21 04:05 UTC
