### ISSUE TITLE
BULK SMS

### ISSUE THREAD

**Issue by shannonmullaney** [brismuth/google-voice-bulk-texter#40] opened 2019-02-26 20:37 UTC
**Describe the bug**
WHEN IM IN GOOGLE VOICE I CLICK BULK SMS AND GET A MESSAGE SAYING ITS NOT ON PAGE . IT WONT OPEN TO SEND BULK TEXTS. THEN  I TRIED GOOGLE HANGOUTS IT OPENS UP THEN IT SAYS PREPARE 
**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment] 2019-02-26 21:04
Please read the support page before creating issues (https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md). This is an exact duplicate of issue #39, which is linked to from there. Feel free to subscribe to that thread.

**Closed by brismuth** 2019-02-26 21:04 UTC
