### ISSUE TITLE
Similar issue to #18

### ISSUE THREAD

**Issue by kimballtoster** [brismuth/google-voice-bulk-texter#24] opened 2019-01-13 04:42 UTC
I sent out a message using the {name} feature.  It successfully sent about 50 messages.  However, I believe it stopped when one of the people replied to the message in the middle of the sending process.  I have tried to restart the sending process from where it was, but the phone numbers now repeatedly load, but don't actually send.  

![image](https://user-images.githubusercontent.com/46640374/51081689-bf3dd100-16b2-11e9-857e-55318f98601e.png)

**Comment by kimballtoster** [comment] 2019-01-13 04:44
Actually, looking at the timing of the messages sent, the texter cut out about 8 minutes before the message was received, so the issue is not in receiving messages.

**Comment by brismuth** [comment] 2019-01-13 04:46
Did it give you any error message when it stopped? And have you tried refreshing the page before continuing with the list?

**Comment by brismuth** [comment] 2019-01-13 05:51
If you could take a screenshot of the error message that would be helpful.

**Comment by brismuth** [comment] 2019-01-13 21:15
Hey @kimballtoster, hope your elders quorum lesson went well today. 😄 

I saw you had some BYU tabs open in your screenshot - if you're in the Provo/Orem area it would be extremely helpful to me to be able to observe this issue directly (assuming it's the same issue that's been reported by other users). I've had no luck reproducing it on my own computer, but if I can see it on yours I might be able to fix it.

If that's something you're willing to help out with, please email me directly. You can find my email address on my GitHub profile (you'll have to be signed in). https://github.com/brismuth

Thanks!

**Comment by brismuth** [comment] 2019-01-18 22:00
Closing as duplicate of #18. You'll want to subscribe to that thread for updates on this issue.

I think the issue may be caused by some rate limiting on Google's end. I'm considering adding a variable wait time between each message (see #25).

@kimballtoster If you are available to meet up and demo the issue to me, it would still be extremely helpful to fixing the problem. Thanks!

**Closed by brismuth** 2019-01-18 22:00 UTC

**Comment by kimballtoster** [comment] 2019-01-26 20:41
Sorry that I have not been able to meet and let you look it over. I have been pretty busy the past while.
