### ISSUE TITLE
Google Voice Bulk Texter Very Slow

### ISSUE THREAD

**Issue by jwright1243** [brismuth/google-voice-bulk-texter#47] opened 2019-03-20 20:25 UTC
**Describe the bug**
Sending texts is painfully slow. We use to use for 5000/week. Now application can only send 1,500/week due to slowness. 

The URL you were on when the problem occurred. 
https://chrome.google.com/webstore/detail/google-voice-bulk-texter/gdplkhplnfgmodalfimcondhmokmekka?hl=en-US

www.dietdoc.com
www.doctalkgo.com

**Expected behavior**
Application is very slow sending out bulk (Google Voice) texts since update in Feb, 2019.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by brismuth** [comment] 2019-03-21 01:48
The only change made to the extension in February was adding support for the Google Voice redesign so the extension would keep working. Is there a particular part of the process that you feel has slowed down? 

How are you even able to send that many texts in a week without Google blocking your account?

**Comment by stride76** [comment] 2019-03-30 13:13
Thanks for this wonderful program but i tried using it with my google voice and its not working. I loaded like 10 number and typed in my message but i noticed its showing the number on my googlevoice and later its gives me error "confirmSent"failed. And i installed the V1.12 version. Please assist. Thanks

**Comment by brismuth** [comment] 2019-04-01 05:00
@jwright1243 closing since I didn’t hear back from you. Feel free to reply and reopen the issue.

@stride76 you’re reporting a separate issue but I think the issue you’re reporting may be a duplicate of #48. Feel free to subscribe to the thread on #48.

**Closed by brismuth** 2019-04-01 05:00 UTC
