### ISSUE TITLE
Bulk texter only sends 1 message

### ISSUE THREAD

**Issue by lfacey** [brismuth/google-voice-bulk-texter#72] opened 2019-07-20 01:51 UTC
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lfacey** [comment] 2019-07-20 01:52
I put in the numbers, and name.  I check the box to accept and send.  It sends the first one but just continues loading the first number and then sends an error report.

**Comment by brismuth** [comment] 2019-07-20 01:54
@Ifacey does your message contain emojis? If so, this is a duplicate of #61.

**Comment by lfacey** [comment] 2019-07-20 01:57
No... this is the message.  Hi {name}! I am grading tonight and see you haven't turned in work for Algebra 2 yet.  Please make sure you turn in your assignments today.  Thank you. Mrs. Facey

**Comment by brismuth** [comment] 2019-07-20 02:00
Interesting. Can you try a simple "test" message to your own number (you can enter your number multiple times) and make sure that works for you?

If that works, it's possible that there's some extra white space in your message that the extension isn't handling or something like that.

**Comment by lfacey** [comment] 2019-07-20 02:00
ok

**Comment by lfacey** [comment] 2019-07-20 02:03
Error.. only sent 1 time.

**Comment by lfacey** [comment] 2019-07-20 02:10
could it be something in my message?

**Comment by brismuth** [comment] 2019-07-20 02:29
It only sent one even when your message was just the word "test"?

**Comment by lfacey** [comment] 2019-07-20 02:32
oh sorry.. i put in the whole message.  Yep it worked when I did test.  So how do I find the empty space?

**Comment by brismuth** [comment] 2019-07-20 02:39
Thanks for trying that. Sorry about the error, not sure what's causing that. Make sure you don't have any double spaces, and make sure you don't have any extra spaces at the end or at the beginning.

**Comment by lfacey** [comment] 2019-07-21 23:34
so this time I did get through 4 messages and then it stopped again.

**Comment by brismuth** [comment] 2019-08-02 19:09
@lfacey are you having this issue on v1.1.5? And to clarify, is the message actually failing to send in Google Voice (out of my control), or is the extension just breaking down even though the message is successfully sending (potentially a bug with the extension)?

**Comment by carusone4** [comment] 2019-08-03 02:00
Did they delete the bulk texter from the google store Brian?

**Comment by brismuth** [comment] 2019-08-03 14:35
@carusone4 yes, but that's not related to this issue/thread. 

See https://github.com/brismuth/google-voice-bulk-texter/issues/73#issuecomment-517812633.

**Comment by carusone4** [comment] 2019-08-03 19:09
Is there anyway I can get it back on my computer, I used it for my business, it was a life saver lol.

**Comment by brismuth** [comment] 2019-08-03 19:20
@carusone4 yes, but again, that's not related to this issue/thread. 

See #73 (comment).

**Closed** 2019-08-06 21:38 UTC
