### ISSUE TITLE
question

### ISSUE THREAD

**Issue by AmeliaPR** [brismuth/google-voice-bulk-texter#150] opened 2021-06-29 19:35 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

not exactly a feature request but a question before I add it to my computer. 
Does this sync with contacts already loaded into google voice? like can I select multiple contacts or do I have to add each contact individually?

**Comment by volkankaban** [comment] 2021-06-29 20:12
I'm wondering is there any way to get a DB connection (columns; name, number), or using a CSV file to create an SMS list? That way we can schedule SMS messages by list...

**Comment by brismuth** [comment] 2021-06-30 02:59
This is a duplicate of #22  - I saw you already commented on there so I'll go ahead and close this one.

**Comment by brismuth** [comment] 2021-06-30 03:00
@volkankaban your request is different, but is a duplicate of #58. Please comment over there - thanks!

**Closed by brismuth** 2021-06-30 02:59 UTC
