### ISSUE TITLE
I just started using this yesterday and love what it can do.  Is there a way to connect to my existing Google Contact list?  Thank you. 

### ISSUE THREAD

**Issue by mrsthewhit** [brismuth/google-voice-bulk-texter#62] opened 2019-05-16 16:07 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brismuth** [comment] 2019-05-17 23:19
I'm glad you're enjoying the app!

This request is a duplicate of #22.

**Closed by brismuth** 2019-05-17 23:19 UTC
