### ISSUE TITLE
Need emojis!!!

### ISSUE THREAD

**Issue by charlotte123456** [brismuth/google-voice-bulk-texter#69] opened 2019-06-25 14:24 UTC
**Describe the bug**
I'm able to send my desired text to multiple people when I don't include emojis. When I do include emojis, it'll send to the first recipient but leads to the error code and will not send to the other people. 

**URL**
https://voice.google.com/u/4/messages?itemId=draft-149D5DA4-32A8-421D-BE79-A6576D328CE0

**Expected behavior**
Send to all recipients and not get caught on one number. 

Says "text failed".

**Comment by brismuth** [comment] 2019-06-26 22:50
Thanks for the report, this is a duplicate of #61. Feel free to subscribe or comment on that thread so you're notified when this is fixed.

**Closed by brismuth** 2019-06-26 22:50 UTC
