### ISSUE TITLE
Text Won't Send Anymore

### ISSUE THREAD

**Issue by mrmikeray** [brismuth/google-voice-bulk-texter#91] opened 2019-08-30 19:38 UTC
**Describe the bug**
For some reason, it stopped sending my messages. It was working fine yesterday morning, I'm not sure what happened.

**Comment by brismuth** [comment] 2019-09-09 03:14
Even though this isn't exactly the same issue, I'm going to close it as a duplicate of #87. Both are almost certainly caused by updates to the Google Voice UI that Google hasn't fully rolled out yet. Once they've rolled out the changes to me I'll update the code to handle this issue. Feel free to subscribe to that issue for updates.

**Closed by brismuth** 2019-09-09 03:14 UTC
