### ISSUE TITLE
FAILED SENDING

### ISSUE THREAD

**Issue by Dennis860** [brismuth/google-voice-bulk-texter#33] opened 2019-01-26 01:51 UTC
Text failed.  Make sure you haven't enable texting via hangouts, as that will disbale sending messages via google voice app.

If error persists, please send this error to the developes

Error::confirmsend" failed

when you click okay, the page will refresh

**Comment by brismuth** [comment] 2019-01-26 05:43
Closing as duplicate of #18. You'll want to subscribe to that thread for updates on this issue.

**Closed by brismuth** 2019-01-26 05:43 UTC
