### ISSUE TITLE
Having the same problem as number #18, #19, and #21. Sent 66 messages fine, now consistently fails. No matter what I do/change

### ISSUE THREAD

**Issue by julietjacksonvip** [brismuth/google-voice-bulk-texter#23] opened 2018-12-31 00:37 UTC
**Describe the bug**
today I downloaded google voice and this extension, sent 66 texts perfectly fine. when it got to number 67 on the list it failed, tried again multiple times changing multiple things (thinking it would solve the issue) but it's none of the things I tried. seems as if it just doesn't want to work which is so disappointing because you did an awesome job of creating something like this 

**URL**
https://voice.google.com/messages?itemId=draft-961BB782-D8FE-471D-A32F-059E7FB58EA8

**Expected behavior**
error "confirmSent" failed.

**Screenshots**

**Additional context**

**Comment by julietjacksonvip** [comment] 2018-12-31 00:53
so I just read more of the solved issues, tried replacing it (160 characters) with a non complex message (15 characters) it worked. so then I tried the complex message again, it worked again for 5 messages then failed. It's almost like, in a simpleton's eye's... that it gets jammed trying to send so much out, give it an easier task relieves and unjams it but doesn't fix it

**Comment by brismuth** [comment] 2018-12-31 02:00
Interesting. And to clarify, are you using the {name} feature or are you just sending long messages? If this issue keeps occurring for you can you maybe send me a screenshot of the whole page when that error occurs?

Thanks, and sorry about the issue.

**Comment by julietjacksonvip** [comment] 2018-12-31 02:14
Not using the name feature just purely copy and pasting a direct line of numbers from my excel file to the "numbers name" section, and typing in something in the "message" section. To help you better understand first time it worked, 66 messages were sent (160 characters), second time it worked, 5 messages were sent, third time it worked, 5 messages sent, fourth time it worked, 15 messages sent. All times ended, with ultimately failing. I read a bit more, and what number #7 experienced seems very similar. I've called the numbers it gets jammed on, and they are still working, US numbers, no +1's, just 10 number... phone numbers. On the last 3 tries I mentioned, it was only 15 character messages that would eventually end in the error pop up

**Comment by julietjacksonvip** [comment] 2018-12-31 02:16
Would you like me to record what's going on to better help? And BTW it's no problem, I just hope we can work together to figure out what it is causing this

**Comment by brismuth** [comment] 2018-12-31 03:54
A recording could be helpful. To clarify, it's failing after a certain number of sends, and then after just removing the previously sent numbers it succeeds some more and fails again?

That sounds like maybe Google Voice is throttling your account or something like that. If that's what's going on maybe I can have the app detect it somehow and handle it more gracefully.

**Comment by julietjacksonvip** [comment] 2018-12-31 04:33
Yes, exactly what you stated in your first two lines of your previous comment. Did the others experiencing this problem ever find a way to fix it? :(

**Comment by brismuth** [comment] 2018-12-31 05:02
I haven't pinpointed the issue or a guaranteed solution on the other open issues yet. :(

Google isn't transparent about their imposed limitations unfortunately and I haven't hit them before myself, so I haven't been able to add handling for them into the app. It's also possible that Google is displaying some kind of warning to you and the extension is unintentionally skipping past it or something like that.

You might try limiting your sends to 50 or so at a time and waiting a few minutes between them. Let me know if that does anything different.

**Comment by julietjacksonvip** [comment] 2018-12-31 05:14
I understand. I will try that and see if it helps tomorrow and let you know. I currently use SA Group Chat in the app store and found your extension while looking for something better. It takes 8 minutes for 120 text messages

**Comment by julietjacksonvip** [comment] 2018-12-31 05:14
Thanks again

**Comment by brismuth** [comment] 2019-01-18 21:59
Closing as duplicate of #18. You'll want to subscribe to that thread for updates on this issue.

I think the issue may be caused by some rate limiting on Google's end. I'm considering adding a variable wait time between each message (see #25).

**Closed by brismuth** 2019-01-18 21:59 UTC
Labels: duplicate
