### ISSUE TITLE
if text has emojis the script keeps going in loop with first phone number on the list

### ISSUE THREAD

**Issue by iomongol** [brismuth/google-voice-bulk-texter#105] opened 2019-12-26 02:17 UTC
if text has emojis the script keeps going in loop with first phone number on the list:

Example:
Wish you a  happy holiday season, pick your own holidays or celebrate all, that's the spirit. 😜 
From somenames. ⛄🏖  
PS Hope all is well!

Doesn't matter, how many emojis are in or location of the same. The script is just looping on the first recipient forever. First SMS is sent though, which is even more weird.

**Comment by brismuth** [comment] 2020-01-07 17:25
Thanks for reporting!

This is a duplicate of #61. You'll want to subscribe to that issue for updates.

**Closed by brismuth** 2020-01-07 17:25 UTC
