### ISSUE TITLE
Google Bulk texter not working properly

### ISSUE THREAD

**Issue by rezaazerr** [brismuth/google-voice-bulk-texter#83] opened 2019-07-31 16:41 UTC
Hi, I have been using the google bulk texter for awhile. Its great. Just recently it has stopped working. The first contact/number goes through, but the text does not load. It keeps on repeating itself until the error message comes. It says "text failed", error:"Startchat"
![Capture](https://user-images.githubusercontent.com/53532590/62230750-16be3880-b388-11e9-84f7-a269e9330193.PNG)
 failed

![Capture](https://user-images.githubusercontent.com/53532590/62230509-8e3f9800-b387-11e9-8eb1-77911224f986.PNG)

**Comment by brismuth** [comment] 2019-07-31 17:59
Duplicate of #75, which is now resolved. You'll need to manually update the extension following these instructions.
https://github.com/brismuth/google-voice-bulk-texter/blob/master/README.md#install-it

**Closed by brismuth** 2019-07-31 17:59 UTC
