### ISSUE TITLE
startChat failed

### ISSUE THREAD

**Issue by Jcunningham14** [brismuth/google-voice-bulk-texter#88] opened 2019-08-23 17:31 UTC
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment] 2019-09-09 03:11
Closing as duplicate of #87. Feel free to subscribe to that issue for updates.

**Closed by brismuth** 2019-09-09 03:11 UTC
