### ISSUE TITLE
Google Voice Bulk Text Editor Failure, Hangouts disabled 

### ISSUE THREAD

**Issue by wjmworks** [brismuth/google-voice-bulk-texter#30] opened 2019-01-21 21:24 UTC
**Describe the bug**

Unable to send bulk texts after 45+ were delivered. Hangouts SMS is/was disabled, then completely logged out of. Tried different numbers, kept getting the message "confirmSent" failed. Now it is saying "fillNumberInput" failed.

**URL**
The URL you were on when the problem occurred. 

https://voice.google.com/u/0/messages?itemId=draft-69BBC9D0-44B1-4B64-A70E-12CC4654712D

**Expected behavior**

That the bulk SMS would continue to send to the entered numbers. 

**Screenshots**
![techsupport](https://user-images.githubusercontent.com/46906455/51499372-03f2f780-1d98-11e9-9fac-0e37d752cdff.jpg)

![techsupport2](https://user-images.githubusercontent.com/46906455/51499627-0c97fd80-1d99-11e9-8110-9968d7b7609d.jpg)

**Additional context**

**Comment by brismuth** [comment] 2019-01-21 21:41
Closing as duplicate of #18. You'll want to subscribe to that thread for updates on this issue.

I think the issue may be caused by some rate limiting on Google's end. I'm considering adding a variable wait time between each message (see #25).

**Closed by brismuth** 2019-01-21 21:41 UTC

**Comment by wjmworks** [comment] 2019-01-21 22:34
Thank you for directing me through this issue. And thank you for making
your work available.
