### ISSUE TITLE
Text entered in BulkSMS doesn't get entered in Hangouts 

### ISSUE THREAD

**Issue by BraveNewMath** [brismuth/google-voice-bulk-texter#2] opened 2018-07-01 15:21 UTC
i am on windows 10 Enterprise, V1709, OS Build 16299.492

Here's a screencast of the issue: https://www.screencast.com/t/WAJ5scoz

Thanks for your time

**Comment by brismuth** [comment] 2018-07-01 18:36
Hi @BraveNewMath, thanks for reporting this issue. It looks like on your chats are opening in a new window instead of on that same page. I think that's due to having the hangouts chrome extension installed.

Right now the project doesn't support interacting with the Hangouts extension, and I'm not sure if that can even be done.

For now you should be able to temporarily disable your hangouts extension, refresh the page, and that should work.

**Comment by brismuth** [comment] 2018-07-09 05:14
@BraveNewMath I also just merged #4, which adds support for sending via the Google Voice interface (voice.google.com) as opposed to the hangouts interface. 

Messaging via the Google Voice interface shouldn't clash with the Hangouts extension, although you'd need to disable Google Voice messaging via Hangouts to use that.

**Comment by amielech** [comment] 2018-09-13 15:33
How do I disable Google Voice messaging via Hangouts?

**Comment by brismuth** [comment] 2018-09-13 15:50
@amielech to clarify, you're saying you have confirmed that Google Voice messaging via Hangouts is disabled, but you're trying to send Google Voice messages via Hangouts?

If you want to send Google Voice Messages via Hangouts, you'll need to make sure that box **is** selected. Then you'll need to refresh the page and it should work.

**Comment by brismuth** [comment] 2018-09-13 15:51
@amielech are you saying you're getting that error on https://voice.google.com? If that's the case, have you verified that you are able to manually send messages on that site? If you can't manually send messages the extension won't work either.

**Comment by amielech** [comment] 2018-09-13 16:10
I am not trying to send messages via hangouts. I have been using voice.google.com for a while. The first few weeks of using the bulk texter it was fine. Now it is not and I'm tired of going trhough and resending. So I am glad you are quick to respond! 

I replied via email with the mp4 screencast video of what it's doing. Did you receive it?

**Comment by amielech** [comment] 2018-09-13 16:27
https://youtu.be/-2p5R4mA2Zk

**Comment by brismuth** [comment] 2018-09-13 18:19
That YouTube link doesn't seem to be working for me. Is it publicly shared?

**Comment by amielech** [comment] 2018-09-13 22:01
https://youtu.be/-2p5R4mA2Zk
No, I don't remember which day. Around or before Aug 17.

**Comment by brismuth** [comment] 2018-09-13 22:29
Geez, sorry about this issue! It sounds like your issue is separate from the one originally reported on this thread so I'm going to move our conversation over to https://github.com/brismuth/google-voice-bulk-texter/issues/6.

**Closed as completed** 2018-10-03 07:22 UTC
Labels: bug
