### ISSUE TITLE
text message don't get sent and error message arrives. 

### ISSUE THREAD

**Issue by jenablue** [brismuth/google-voice-bulk-texter#50] opened 2019-03-30 20:28 UTC
**Describe the bug**
I send 25 messages every 10-15 mins. I keep seeing the number slot filled and the message space filled but does not send. It will keep doing this for the first recipient and never move to the next. So I have to sit and hit send every time the green send arrow lights up. 
**URL**
https://voice.google.com/u/0/messages?itemId=draft-9260D52A-9BDF-4DA1-8915-3211665E7566

**Expected behavior**
I expect to be able to send the messages as I have prior to two days ago. 
**Screenshots**
![image](https://user-images.githubusercontent.com/49100643/55281348-02e2c700-5301-11e9-922b-cec5f0ed4417.png)

**Additional context**
I get an error message 
I really like this app. I get to reference go back to past text. Please fix it. 

I can not show exactly an image due to the privacy of my clients.

**Comment by brismuth** [comment] 2019-04-01 04:58
Thanks for reporting, and including screenshots. This seems to be a duplicate of #48, going to close this and track the issue there. Feel free to subscribe to that thread.

**Closed by brismuth** 2019-04-01 04:58 UTC
