### ISSUE TITLE
Having the same issue as #18

### ISSUE THREAD

**Issue by tevdev** [brismuth/google-voice-bulk-texter#21] opened 2018-12-29 01:46 UTC
It's really strange because I used it this Christmas to send a Christmas mas text to like 100 people and now it doesn't want to work....

**Comment by brismuth** [comment] 2018-12-29 22:02
Sorry, I haven't been able to reproduce this on my end, so I haven't been able to determine what is causing the issue. Any additional detail you can provide would be helpful

**Comment by brismuth** [comment] 2019-01-18 21:53
Closing as duplicate of #18. You'll want to subscribe to that thread for updates on this issue.

**Closed by brismuth** 2019-01-18 21:53 UTC
Labels: duplicate

**Comment by tevdev** [comment] 2019-01-22 00:08
No problem. I think I might have been exceeding the character limit.
