### ISSUE TITLE
Google Voice Bulk Texter not recognizing "check" in box accepting usage policy

### ISSUE THREAD

**Issue by enlightenedbrittany** [brismuth/google-voice-bulk-texter#63] opened 2019-05-17 21:50 UTC
After clicking "send messages" red text appears that says "Please read the Google Voice Acceptable Use Policy and check the box below." It is already checked though. 

I've unchecked it. Logged out. Logged back in, then checked it. Same result.

**Comment by brismuth** [comment] 2019-05-17 23:19
Interesting. I haven't heard of this happening before, and I'm not able to reproduce the issue. Can you record a video of this happening?

One thing you can try is uninstalling the extension and reinstalling it. Has the extension worked for you before?

**Comment by maritaproudground** [comment] 2019-05-23 21:41
this is happening to me too.

**Comment by brismuth** [comment] 2019-06-19 17:20
@nsbutler @maritaproudground @enlightenedbrittany can one of you try disabling all other extensions and see if this still happens? Also, can you make sure Chrome is fully up to date?

**Comment by zqvyh** [comment] 2019-07-01 19:24
Hello, this is also happening to me. Chrome is updated; I uninstalled and reinstalled the extension; I logged out of and back into Chrome; I restarted Chrome; I cleared my cookies; I restarted my computer. None of this worked. Thanks for your support!

**Comment by zqvyh** [comment] 2019-07-01 19:25
I also disabled all other extensions. This didn't work either.

**Comment by brismuth** [comment] 2019-07-01 19:26
@zqvyh can you try disabling your other extensions temporarily to see if that resolves the issue?

**Comment by brismuth** [comment] 2019-07-01 19:26
Ok, thanks for the info. Still haven't been able to replicate this on my end.

**Comment by czakon123** [comment] 2019-07-10 21:06
Same thing just happened to me. I am not sure if it does this because it is saying my use violates the policy. I was able to use it just an hour ago.

**Comment by brismuth** [comment] 2019-07-10 21:11
So you're saying you used it just an hour ago and didn't have the issue? Did you change anything between then and now in Chrome? Also, can you try changing the message to be a simple "test" message and the number to be your own number, just to rule out one of them causing this issue somehow?

**Comment by czakon123** [comment] 2019-07-10 21:16
I was able to send myself a test message so not sure why it wouldn't allow me earlier with multiple numbers.

**Comment by brismuth** [comment] 2019-07-10 21:19
After looking into the code again, it looks like that message will show up if certain errors occur while preparing to send texts. If I had the values you're using for those two inputs then I'd possibly be able to reproduce the issue on my end and should be able to fix it.

**Comment by brismuth** [comment] 2019-07-10 21:21
I was just able to reproduce this issue by not including any numbers at all in the number input.

I'll fix the verification code, but you should double check that the phone numbers are correctly formatted, as shown in the example in the popup.

**Comment by brismuth** [comment] 2019-07-10 21:45
@enlightenedbrittany @maritaproudground @zqvyh @czakon123 - this issue is now fixed in v1.1.4. 

Your extension should update automatically within the next day or so. Alternatively, you can uninstall and reinstall the extension to force it to update once you see that v1.1.4 is available here:
https://chrome.google.com/webstore/detail/google-voice-bulk-texter/gdplkhplnfgmodalfimcondhmokmekka?hl=en-US

You can see the current version under "Additional Information". v1.1.4 should be available at that link within the next hour or so.

![image](https://user-images.githubusercontent.com/5679695/61007237-8f058100-a329-11e9-971d-7cbfe40777c5.png)

**Closed by brismuth** 2019-07-10 21:45 UTC
Labels: bug

**Comment by czakon123** [comment] 2019-07-10 21:54
Thanks so much for prompt response.
