### ISSUE TITLE
Google bulk texter won't send messages 

### ISSUE THREAD

**Issue by nsbutler** [brismuth/google-voice-bulk-texter#67] opened 2019-06-10 14:55 UTC
**Describe the bug**
When I go to send messages it gives me this message "Please read the Google Voice Acceptable Use Policy and check the box below." Once I follow the steps it does not resolve. Uninstalling and reinstalling the plugin does not work. 
**URL**
The URL you were on when the problem occurred. 

**Expected behavior**
The messages were sending perfectly before, and my Google voice account is working 
**Screenshots**

**Additional context**

**Comment by brismuth** [comment] 2019-06-19 17:19
Closing as a duplicate of #63. You can comment on that thread or subscribe to it for updates. 

I'm not sure how to reproduce this still.

**Closed by brismuth** 2019-06-19 17:19 UTC
