### ISSUE TITLE
Additional fields (e.g. address)

### ISSUE THREAD

**Issue by donnyPD** [brismuth/google-voice-bulk-texter#68] opened 2019-06-21 16:12 UTC
I'd like to know if it is possible to add additional special fields into the text. For example. I am in Real Estate and would like to send a message that includes the address of that person, can I use a special field like we currently have for {name}? and have the message be something like this:
_Hi {name}!_
_My name is Jackie. Through public record, your name came up and it looks like you may have a glitch with your property at **{address}**. If you have an interest in discussing your options and possibly selling your home, please text or call and I’d be happy to chat with you._

Thank you
Donny

**Comment by brismuth** [comment] 2019-06-21 18:05
Closing as a duplicate of #49. You can comment on that thread or subscribe to it for updates.

**Closed by brismuth** 2019-06-21 18:05 UTC
